name: CI

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci

    - name: Publish
      uses: lannonbr/vsce-action@master
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

    - name: Package
      uses: lannonbr/vsce-action@master
      with:
        args: "package"

    - name: Get package name
      id: get_package_name
      run: |
        echo "::set-output name=name::$(echo vscode-ghc-simple-*.vsix)"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: extension-package
        path: ${{ steps.get_package_name.name }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Version ${{ github.ref }}

    - name: Upload release
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.get_package_name.name }}
        asset_name: ${{ steps.get_package_name.name }}
        asset_content_type: application/vsix
